const Ziggy = {
    "url":"http:\/\/127.0.0.1:8000",
    "port":null,
    "defaults":{},
    "routes":{
        "sanctum.csrf-cookie":{
            "uri":"sanctum\/csrf-cookie",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "ignition.healthCheck":{
            "uri":"_ignition\/health-check",
            "methods":["GET","HEAD"]},
        "ignition.executeSolution":{
            "uri":"_ignition\/execute-solution",
            "methods":["POST"]},
        "ignition.updateConfig":{
            "uri":"_ignition\/update-config",
            "methods":["POST"]},
        "dashboard":{
            "uri":"dashboard",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "items.index":{
            "uri":"items",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "items.store":{
            "uri":"items",
            "methods":["POST"],
            "middleware":["web"]},
        "items.update":{
            "uri":"items/{item}",
            "methods":["PUT"],
            "middleware":["web"]},
        "items.destroy":{
            "uri":"items/{item}",
            "methods":["DELETE"],
            "middleware":["web"]},
        "borrowed-items.index":{
            "uri":"borrowed-items",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "borrowed-items.store":{
            "uri":"borrowed-items",
            "methods":["POST"],
            "middleware":["web"]},
        "borrowed-items.totalBorrowedQuantityPerItem":{
            "uri":"total-borrowed-quantity-per-item",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "borrowed-items.return":{
            "uri":"borrowed-items/return",
            "methods":["POST"],
            "middleware":["web"]},
        "borrowed-items.totalOverdueQuantitiesPerItem":{
            "uri":"total-overdue-quantities-per-item",
            "methods":["POST"],
            "middleware":["web"]},
        "damaged-items.index":{
            "uri":"damaged-items",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "damaged-items.store":{
            "uri":"damaged-items",
            "methods":["POST"],
            "middleware":["web"]},
        "damaged-items.repair":{
            "uri":"damaged-items/repair",
            "methods":["POST"],
            "middleware":["web"]},
        "profile.edit":{
            "uri":"profile",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "profile.update":{
            "uri":"profile",
            "methods":["PATCH"],
            "middleware":["web"]},
        "profile.destroy":{
            "uri":"profile",
            "methods":["DELETE"],
            "middleware":["web"]},
        "login":{
            "uri":"login",
            "methods":["GET","HEAD"],
            "middleware":["web"]},
        "logout":{
            "uri":"logout",
            "methods":["POST"],
            "middleware":["web"]},
    }
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
